apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bkci-environment
  name: bkci-environment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bkci-environment
  template:
    metadata:
      labels:
        app: bkci-environment
    spec:
      containers:
        - image: {{ .Values.image.hub }}/bkci-environment:{{ .Values.image.tag }}
          name: bkci-environment
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /data/docker/bkci/ci/backend/
          command: 
            - '/bin/sh'
            - '-c'
            - 'ln -s /data/docker/bkci/public/ci/environment/packages /data/docker/bkci/ci/agent-package/packages ; 
               ln -s /data/docker/bkci/public/ci/environment/jre /data/docker/bkci/ci/agent-package/jre ;
               /data/docker/bkci/ci/backend/module_run.sh'
          env:
            - name: CONSUL_SERVER
              value: {{ .Values.consul.server }}
            - name: BK_CI_ENV
              value: {{ .Values.env.BK_CI_ENV}}
            - name: NODE_IP
              valueFrom:
                fieldRef:
                    fieldPath: status.hostIP
          volumeMounts:
            - mountPath: "/data/docker/bkci/public/ci/environment"
              name: nfs-agent-package
      volumes: 
        - name: nfs-agent-package
          persistentVolumeClaim: 
            claimName: nfs-agent-package