apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bkci-image
  name: bkci-image
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bkci-image
  template:
    metadata:
      labels:
        app: bkci-image
    spec:
      containers:
        - image: {{ .Values.image.hub }}/bkci-image:{{ .Values.image.tag }}
          name: bkci-image
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /data/docker/bkci/ci/backend/
          command: ['/bin/sh','-c','/data/docker/bkci/ci/backend/module_run.sh']
          env:
            - name: CONSUL_SERVER
              value: {{ .Values.consul.server }}
            - name: BK_CI_ENV
              value: {{ .Values.env.BK_CI_ENV}}
            - name: BK_CI_CONSUL_DISCOVERY_TAG
              value: {{ .Values.env.BK_CI_CONSUL_DISCOVERY_TAG}}
            - name: NODE_IP
              valueFrom:
                fieldRef:
                    fieldPath: status.hostIP
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock