apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bkci-notify
  name: bkci-notify
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bkci-notify
  template:
    metadata:
      labels:
        app: bkci-notify
    spec:
      containers:
        - image: {{ .Values.image.hub }}/bkci-notify:{{ .Values.image.tag }}
          name: bkci-notify
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /data/docker/bkci/ci/backend/
          command: ['/bin/sh','-c','/data/docker/bkci/ci/backend/module_run.sh']
          env:
            - name: CONSUL_SERVER
              value: {{ .Values.consul.server }}